name: Run Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: self-hosted

    steps:
      # Krok 1: Budowanie projektu
      - name: Build project
        run: dotnet build --no-restore --configuration Release

      # Krok 2: uuchoninie testów
      - name: RecipesSupport.Tests
        run: dotnet test RecipesSupport.Tests --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

      # Krok 3: Publikacja wyników testów (opcjonalne)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.trx'
